cursor_shape Underline
cursor_underline_thickness 2
window_padding_width 20

# Special
foreground              #c8d3f5
background              #0b0c14

# Black
color0                  #0f111a
color8                  #1a1b26

# Red
color1                  #ff757f
color9                  #ff9aa2

# Green 
color2                  #8bd49c
color10                 #a6e3b9

# Yellow
color3                  #ffc777
color11                 #ffd580

# Blue
color4                  #82aaff
color12                 #9ecbff

# Magenta
color5                  #c099ff
color13                 #d5b6ff

# Cyan 
color6                  #7dcfff
color14                 #b4f9f8

# White
color7                  #c8d3f5
color15                 #e6edf3

# Cursor
cursor                  #9ecbff
cursor_text_color       #0b0c14

# Selection
selection_foreground    #ffffff
selection_background    #1f2335

